# Generated by Django 4.2.8 on 2026-03-03 21:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('request_type', models.CharField(choices=[('order', 'Заказ товара'), ('callback', 'Обратный звонок'), ('consultation', 'Консультация'), ('question', 'Вопрос'), ('complaint', 'Жалоба')], default='order', max_length=20, verbose_name='Тип заявки')),
                ('product_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название товара')),
                ('product_weight', models.CharField(blank=True, help_text='Например: 1 кг, 500 г, 2 шт', max_length=100, null=True, verbose_name='Вес/Количество')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество товара')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация от клиента', null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('called', 'Звонили'), ('waiting', 'Ожидание'), ('processing', 'Обработка'), ('completed', 'Завершена'), ('rejected', 'Отклонена'), ('spam', 'Спам')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('honeypot', models.CharField(blank=True, max_length=200, verbose_name='Honeypot (для спам-фильтра)')),
                ('notes', models.TextField(blank=True, help_text='Личные заметки о заявке', null=True, verbose_name='Заметки администратора')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='requests_ap_status_9ff2a5_idx'), models.Index(fields=['phone'], name='requests_ap_phone_cdf02d_idx'), models.Index(fields=['email'], name='requests_ap_email_09e6a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование'), ('status_change', 'Изменение статуса'), ('delete', 'Удаление'), ('export', 'Экспорт')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests_app.customerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Лог администратора',
                'verbose_name_plural': 'Логи администратора',
                'ordering': ['-timestamp'],
            },
        ),
    ]
