# Generated by Django 4.2.8 on 2026-03-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='order_details',
            field=models.TextField(blank=True, help_text='JSON или текст с полным содержимым корзины', null=True, verbose_name='Детали заказа'),
        ),
    ]
