# Generated by Django 4.2.8 on 2026-03-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_customerrequest_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='order_details',
            field=models.TextField(blank=True, help_text='JSON с полным содержимым корзины - каждый товар с именем, ценой, количеством', null=True, verbose_name='Детали заказа (JSON)'),
        ),
    ]
